### PR TITLE
Add `remark-videos` to list of plugins

### PR DESCRIPTION
**Pull request by Chailotl**
### Initial checklist

*   [x] I read the support docs 
*   [x] I read the contributing guide 
*   [x] I agree to follow the code of conduct 
*   [x] I searched issues and couldn’t find anything (or linked relevant results below) 
*   [x] If applicable, I’ve added docs and tests

### Description of changes

I added a link to the [remark-videos](https://github.com/Chailotl/remark-videos) plugin that I developed.

### CODE REVIEW

**Comment by Chailotl** [comment]
> Generating HTML is better done in a rehype plugin.

I saw some remark plugins that generate HTML, such as `remark-callouts`, and to me it logically makes more sense as a remark plugin because it operates on markdown syntax, but I'll give it some thought.

> It would be nice if the plugin accept an option to allow different file extensions.

The `<video>` tag already works with any video extension. This plugin just puts the video file link into the `src` attribute.

> It would be nice if the plugin handles alt descriptions.

That's a fair suggestion, I'll look into adding it.

**Comment by ChristianMurphy** [comment]
Welcome @Chailotl!
Thanks for sharing!

> The `<video>` tag already works with any video extension.

The `<video>` tag does, this plugin currently only works for MP4.
https://github.com/Chailotl/remark-videos/blob/851c332993210e6f091453f7ed887be24492bcee/index.js#L7
There are a lot more, consider leveraging https://www.npmjs.com/package/is-video or https://github.com/sindresorhus/video-extensions

> I saw some remark plugins that generate HTML, such as `remark-callouts`

Those add new syntax features to markdown, they need to integrate with the parser.
This plugin does not, it can work on the HTML syntax tree.

**Comment by ChristianMurphy** [comment]
No worries!

Some other ideas:
1. consider adding more automation like:
   1. adding some test cases with `node:test` to make it easier to confirm the plugin works and easier for others to contribute
   2. leveraging lint and formatting tools like `xo` and `prettier` for code style and structure consistency
   3. using GitHub actions to automatically run tests and lint checkers for new contributions
2. consider leveraging JSDoc + TypeScript for automated option checking and better autocomplete https://www.typescriptlang.org/docs/handbook/jsdoc-supported-types.html (this also benefits non-typescript users leveraging an IDE)
3. consider annotating the project as side effect free for better optimization from build tools https://webpack.js.org/guides/tree-shaking/#mark-the-file-as-side-effect-free

> It would be nice if the plugin handles alt descriptions

Adding on to this.
Images have both alt and title text
```md
![alternate text](http://example.com/url "title text")
```

---

alternate text

---

There could be an opportunity to offer some combination of:
* SRT/webVTT track as an alternate to audio https://developer.mozilla.org/en-US/docs/Learn/Accessibility/Multimedia#video_text_tracks
* fallback if video is not supported https://developer.mozilla.org/en-US/docs/Learn/Accessibility/Multimedia#accessible_audio_and_video_controls
* multiple video source tracks
*

**Comment by wooorm** [comment]
Closing this as it seems abandoned. This also makes more sense as a rehype plugin I think!

**Pull request closed without merging**
