### PR TITLE
Ignore package-lock.json files

### PR DESCRIPTION
**Pull request by remcohaszing**
They are generated by lerna, but the policy is to not commit them.

### CODE REVIEW

**Comment by ChristianMurphy** [comment]
@remcohaszing did you find a case where lockfiles were generated?
The npmrc should be preventing that :thinking: 
https://github.com/remarkjs/remark/blob/da8203283a4759f29a58ea1782c16123f9805f0a/.npmrc#L1

**Comment by BarryThePenguin** [comment]
I think running `npm install` from a package directory would generate one

**Comment by wooorm** [comment]
Yeah, I would think `.npmrc` should’ve prevented it indeed, but as @remcohaszing saw this pop up I’m assuming this was somehow not working 100% 🤷‍♂️

**Comment by remcohaszing** [comment]
There’s a top level `.npmrc` file. Since the subpackages are installed using `lerna`, their `package-lock.json` files were still being generated.

**Pull request merged**
