### PR TITLE
Add `remark-remove-comments` to list of plugins

### PR DESCRIPTION
**Pull request by alvinometric**
Hello everyone,

Thank you so much for your work on Remark, the ecosystem is fantastic. This PR adds my plugin [remark-remove-comments](https://github.com/alvinometric/remark-remove-comments) to the list in `plugins.md`.

This is my first plugin! Feel free to share any kind feedback, I would love that. I took inspiration from `remark-toc` for the Readme so hopefully it's clear enough. It's been tested with the latest version of Remark.

Thanks!
Alvin

### CODE REVIEW

**Review by wooorm — APPROVED** [review]

**Comment by wooorm** [comment]
Code looks great, thanks Alvin!

**Comment by alvinometric** [comment]
This is fantastic to hear, thank you for the review! Now on to making the Gatsby version 😄

**Comment by wooorm** [comment]
You may like https://github.com/kevin940726/to-gatsby-remark-plugin for that!

**Comment by alvinometric** [comment]
Oh wow, this is amazing! Thank you 🎉

**Pull request merged**
