### PR TITLE
Fix parsing blank line containing spaces

### PR DESCRIPTION
**Pull request by tuttieee**
Closes GH-473

Create a "blank-line" tokenizer to replace the current "new-line" tokenizer.
It follows the definition of "blank lines" written in CommonMark spec:
* https://spec.commonmark.org/0.29/#blank-line
* https://spec.commonmark.org/0.29/#blank-lines

### CODE REVIEW

**Comment by tuttieee** [comment]
Good point.
I think modern browsers have sophisticated performant regex engines containing techniques like pre-compiling though,
I evaluated the performance compared to an alternative implementation below, which does not use regex:

<details>
<summary>An alternative implementation of blank line tokenizer</summary>

```js
'use strict'

var space = ' '
var tab = '\t'
var lineFeed = '\n';

function isBlankLineChar(char) {
  return char === space || char === tab || char === lineFeed;
}

module.exports = blankLine

function blankLine(eat, value, silent) {
  var character
  var subvalue = ''
  var index = 0
  var length = value.length

  while (index < length) {
    character = value.charAt(index);
    if (!isBlankLineChar(character)) {
      break;
    }

    index++
    subvalue += character
  }

  if (subvalue === '') {
    return
  }

  /* istanbul ignore if - never used (yet) */
  if (silent) {
    return true
  }

  eat(subvalue)
}
```
</details>

And the test code and environment information are below:
<details>
<summary>A performance testing code</summary>

```js
'use strict'

var microBenchmark = require('micro-benchmark')
var remark = require('../packages/remark')

var input0 = '\nFilled line'
var input10 = ' '.repeat(10) + '\nFilled line'
var input100000 = ' '.repeat(100000) + '\nFilled line'

var result = microBenchmark.suite({
  specs: [
    {
      name: 'blank line with no space',
      fn: function() {
        remark().parse(input0)
      }
    },
    {
      name: 'blank line with 10 spaces',
      fn: function() {
        remark().parse(input10)
      }
    },
    {
      name: 'blank line with 100000 spaces',
      fn: function() {
        remark().parse(input100000)
      }
    }
  ]
})

var report = microBenchmark.report(result)
console.log(report)
```

To run this code, you have to install [micro-benchmark](https://www.npmjs.com/package/micro-benchmark).
```shell
npm install micro-benchmark
```

</details>

The environment was
OS: macOS Mojave 10.14.6
Hardware: MacBook Pro (13-inch, 2017, Two Thunderbolt 3 ports)
CPU: 2.3 GHz Intel Core i5
Memory: 16 GB 2133 MHz LPDDR3
Env: node 10.16.0

## Results

### The implementation using regex
```
Name                             Operations per second    Average time, ms
blank line with no space         4.1 x 10^3               0.24                ==============================>
blank line with 10 spaces        4.0 x 10^3               0.25                =============================>
blank line with 100000 spaces    2.8 x 10^3               0.36                ====================>
```

### The alternative implementation not using regex
```
Name                             Operations per second    Average time, ms
blank line with no space         4.2 x 10^3               0.24                ==============================>
blank line with 10 spaces        4.0 x 10^3               0.25                =============================>
blank line with 100000 spaces    297                      3                   ==>
```

These show that
* There is no difference between the two implementations in practical cases where the number of spaces is zero or few.
* When the number of spaces is extremely large, regex is much faster than looping characters one by one.

In addition, I think, because the current `newline` tokenizer already uses regex, the new code in this PR will not be so much worse than the current one.
https://github.com/remarkjs/remark/blob/master/packages/remark-parse/lib/tokenize/newline.js#L33
https://github.com/wooorm/is-whitespace-character/blob/master/index.js#L11

Please let me know if there is something wrong, anther implementation that I have to compare, or so.

**Comment by tuttieee** [comment]
And what does "IME tokenizers" mean here?
I'm not sure this code is related to IMEs.

**Comment by wooorm** [comment]
@tuttieee IME means “in my experience”, in this case, probably!

**Comment by tuttieee** [comment]
oh, thanks. Sorry for my poor English.

**Comment by tuttieee** [comment]
but yes, it's a possible option to switch to the non-regex one, which may be slightly faster in case of few spaces.

**Pull request merged**
