### PR TITLE
Add `remark-github-blockquote-alert` to list of plugins

### PR DESCRIPTION
**Pull request by jaywcjlove**
### Initial checklist

*   [x] I read the support docs 
*   [x] I read the contributing guide 
*   [x] I agree to follow the code of conduct 
*   [x] I searched issues and couldn’t find anything (or linked relevant results below) 
*   [x] If applicable, I’ve added docs and tests

### Description of changes

Add [`remark-github-blockquote-alert`](https://github.com/jaywcjlove/remark-github-blockquote-alert)

### CODE REVIEW

**Comment by ChristianMurphy** [comment]
Hey @jaywcjlove!
Thanks for sharing!

This appears to focus on the HTML output and does not modify the markdown?
If so you may want to consider a rehype plugin instead.

There is one https://github.com/chrisweb/rehype-github-alerts which may suit your needs.
There is also an open issue on https://github.com/rehypejs/rehype-github/issues/3 which could standardize this if needed.

**Comment by jaywcjlove** [comment]
@ChristianMurphy Oh, I didn't pay attention to it.

**Comment by wooorm** [comment]
[remark-github-beta-blockquote-admonitions](https://github.com/myl7/remark-github-beta-blockquote-admonitions) is listed already too.
And indeed, perhaps better to do this in HTML/rehype, [chrisweb/rehype-github-alerts](https://github.com/chrisweb/rehype-github-alerts)?

What should we do with this PR? @jaywcjlove @ChristianMurphy?

**Comment by jaywcjlove** [comment]
Both `remark-github-beta-blockquote-admonitions` and `rehype-github-alerts` have historical baggage, supporting old syntax, which should now be removable.

`remark-github-beta-blockquote-admonitions` does not generate icons, so you need to add icons manually through CSS.

Therefore, I think `rehype-github-alerts` is better.

`remark-github-blockquote-alert` did not implement the old syntax and instead expanded with a new syntax for internationalization, as follows:

```markdown
> [!NOTE]  
> Useful information that users should know, even when skimming content.
```

@wooorm  So I should only use my own `remark-github-blockquote-alert`.

@wooorm @ChristianMurphy I forgot to ask if merging another option would be possible. If not needed, I will close it.

**Comment by wooorm** [comment]
To summarize, you are saying:

* `remark-github-beta-blockquote-admonitions` is not really maintained
* `rehype-github-alerts` is maintained but *also* includes code for an older syntax.

> remark-github-blockquote-alert

I do wonder about what Christian also asked: would a rehype plugin not be better?

And if you’d make it a rehype plugin, then it would be almost the existing `rehype-github-alerts`. Is it really worth it to have 2 plugins?

**Comment by jaywcjlove** [comment]
When I was developing this plugin, I was only aiming to solve the issue in my other package https://github.com/uiwjs/react-markdown-preview/issues/258, and added an internationalization option for another project of mine. I didn't pay attention to `rehype-github-alerts` at that time. Now it has been integrated into multiple projects of mine, `remark-github-blockquote-alert` has completed its mission on my side.

If `rehype-github-alerts` removes support for the old syntax and supports the special syntax I want, `> [!NOTE/笔记]`, I am willing to abandon my project.

@wooorm

**Comment by wooorm** [comment]
> remark-github-blockquote-alert has completed its mission on my side.

That sounds like you are not interested in maintaining your project? 🤔

> the special syntax I want,

🤔 That sounds like your project does *not* match GitHub? It matches GH in some ways, but also matches your own preferences?

**Comment by jaywcjlove** [comment]
> > remark-github-blockquote-alert has completed its mission on my side.
> 
> That sounds like you are not interested in maintaining your project? 🤔
> 
> > the special syntax I want,
> 
> 🤔 That sounds like your project does _not_ match GitHub? It matches GH in some ways, but also matches your own preferences?

I have contributed to nearly [300 code repositories](https://github.com/search?q=user:jaywcjlove+user:uiwjs+user:tsbbjs+user:kktjs+user:antdpro+user:JSLite+archived:false&type=Repositories) in the open-source community and published over [500 packages](https://www.npmjs.com/~wcjiang) through npm. However, things have been tough lately. I lost my job at the end of last year, and I currently have no income and haven't managed to overcome this situation yet. Recently, someone raised a [new issue (#258)](https://github.com/uiwjs/react-markdown-preview/issues/258) in a project, and I noticed that the needed plugins were not listed in the remark and rehype projects. However, I found the solution to this problem to be quite simple, so I started developing a new package to address it.


I have contributed 4 plugins to rehype and have been actively maintaining them. I simply feel that if there are two similar plugins, the official preference is to keep only one, and I am willing to abandon my own.


image

@wooorm

**Comment by wooorm** [comment]
> I have contributed to nearly 300 code repositories in the open-source community and published over 500 packages through npm.

Yes, I know you’re prolific and contribute a lot! 😊 I appreciate it!

> However, things have been tough lately. I lost my job at the end of last year, and I currently have no income and haven't managed to overcome this situation yet.

I am sorry to hear that!

> I have contributed 4 plugins to rehype and have been actively maintaining them. I simply feel that if there are two similar plugins, the official preference is to keep only one, and I am willing to abandon my own.

Right, good point.

---

I am fine adding this for now. If it becomes unmaintained, or people have problems with the mistmatch between what it does and what they think it does, we can revisit this later!

**Pull request merged**
