### PR TITLE
remark-parse: stricter link parsing for whitespace between display te…

### PR DESCRIPTION
**Pull request by samouri**
Addresses https://github.com/remarkjs/remark/issues/456

### CODE REVIEW

**Comment by ChristianMurphy** [comment]
@samouri could you look into the four tests that are now failing?
https://travis-ci.org/remarkjs/remark/jobs/622799426

**Comment by wooorm** [comment]
@samouri Running `node script/regenerate-fixtures` regenerates fixtures. They are probably testing the previous behaviour.

**Comment by samouri** [comment]
@ChristianMurphy: do you know when we'll be able to merge this PR?

**Comment by ChristianMurphy** [comment]
Generally for changes to remark (core), especially major ones, I'd prefer to have more than one member of the core team to sign off.
I've pinged the merger team to see if we can get another set of eyes.
Hopefully this can be merged soon.

**Comment by wooorm** [comment]
Heya, sorry, I've been blocking this by not reviewing. I think this looks good but as it's a breaking change I'd like to delay a bit before landing. I'm thinking it's time for a new major in about 1 or 2 months?

**Comment by samouri** [comment]
Thanks @wooorm 🎉 !!

**Comment by wooorm** [comment]
Thank you for working on it!

**Pull request merged**
