### PR TITLE
Added remark-jargon plugin

### PR DESCRIPTION
**Pull request by joostdecock**
I wrote a plugin, so I added it to the list.
If that's not how things are supposed to work, please ignore this.

### CODE REVIEW

**Comment by wooorm** [comment]
Nice! I would like to suggest that you also include some more info on how remark users can install and use this, without gatsby!

P.S. `term.length` -> `term.length`!

**Comment by joostdecock** [comment]
Yes, indeed. I need to setup a minimal repo to use this with remark only. It's not my use-case, so I haven't done it yet, but I have created an issue for it here: https://github.com/freesewing/freesewing/issues/163  I hope to get around to it soon.

Thanks for spotting the length typo.

**Comment by joostdecock** [comment]
Ok, [README](https://github.com/freesewing/freesewing/tree/develop/packages/remark-jargon) updated. I've also setup a [minimal repo](https://github.com/joostdecock/remark-jargon-example) that shows its use.

I've fixed that typo too. I need to do a few other things before publishing an updated version but it will be done no later than tomorrow.

**Comment by wooorm** [comment]
Nice! ✨

**Comment by joostdecock** [comment]
Thank you 🙏

**Pull request merged**
