### PR TITLE
Add improved docs on what this project is

### PR DESCRIPTION
**Pull request by BeLi4L**
### Initial checklist

*   [x] I read the support docs 
*   [x] I read the contributing guide 
*   [x] I agree to follow the code of conduct 
*   [x] I searched issues and couldn’t find anything (or linked relevant results below) 
*   [x] If applicable, I’ve added docs and tests

### Description of changes

Go from this:

image

to this:

image

### CODE REVIEW

**Review by remcohaszing — APPROVED** [review]
Thanks!

**Comment by wooorm** [comment]
Hmm, this is intentional. Treating them as sentences in an existing paragraph, I think is arguably more correct, but also makes things smaller.

Why do you think the current actual behavior is wrong? And yours is better?

**Comment by BeLi4L** [comment]
When I first landed on this page, I didn't see the inline `In:`, so I was confused that the output block had a title, but the input block didn't have any, until I realized it was inline.

It feels more logical to me to have `In/Out` titles like this, it gives a proper structure to the example, it's more consistent and thus make more sense to me. 

If you think that it breaks the flow of the sentence, a solution could be to simply add a colon at the end, like:

```markdown
You can use plugins to turn markdown into HTML:

**In**:

...

**Out**:

...
```

What do you think?

**Comment by wooorm** [comment]
Maybe it’s better to just use actual words, sentences, and not make them “labels”:

* `**In**:` -> `This markdown:`
* `**Plugin**:` -> `…with this plugin:`
* `**Out**:` -> `…yields the following HTML:`

**Comment by wooorm** [comment]
Hmm, agreed that it isn’t great yet.

> > This library turns markdown into HTML.

> Without any mentions to "plugins" since it's not in the following example

The plugin is needed (`remark-html`), otherwise there is no HTML.

---

This section is to very quickly show what this project can do, what plugins can do.
This is already explained in words earlier.
And concrete examples are given later.
Plugins can do millions of things.
The goal here is: two very short examples of input/output to illustrate that.

Perhaps that’s just impossible to do. How about we make the examples shorter, but add optional detailed info?

What about:

````markdown
## What is this?

With this project and a plugin, you can turn this markdown:

```markdown
# Hello, *Mercury*!
```

…into the following HTML:

```html
<h1>Hello, <em>Mercury</em>!</h1>
```

<details><summary>Show example code</summary>

```js
import {unified} from 'unified'
import remarkParse from 'remark-parse'
import remarkHtml from 'remark-html'

const file = await unified()
    .use(remarkParse)
    .use(remarkHtml)
    .process('# Hello, *Mercury*!')

console.log(String(file)) // => '<h1>Hello, <em>Mercury</em>!</h1>'
```

</details>

With another plugin, you can turn this markdown:

```markdown
# Hi, Saturn!
```

…into the following markdown:

```markdown
## Hi, Saturn!
```

<details><summary>Show example code</summary>

```js
import {unified} from 'unified'
import remarkParse from 'remark-parse'
import remarkStringify from 'remark-stringify'
import {visit} from 'unist-util-visit'

const file = await unified()
    .use(remarkParse)
    .use(myRemarkPluginToIncreaseHeadings)
    .use(remarkStringify)
    .process('# Hi, Saturn!')

console.log(String(file)) // => '## Hi, Saturn!'

/** @type {import('unified').Plugin<[], import('mdast').Root>} */
function myRemarkPluginToIncreaseHeadings() {
  return (tree) => {
    visit(tree, (node) => {
      if (node.type === 'heading') {
        node.depth++
      }
    })
  }
}
```

</details>
````

This renders like:

----

## What is this?

With this project and a plugin, you can turn this markdown:

```markdown
# Hello, *Mercury*!
```

…into the following HTML:

```html
<h1>Hello, <em>Mercury</em>!</h1>
```

<details><summary>Show example code</summary>

```js
import {unified} from 'unified'
import remarkParse from 'remark-parse'
import remarkHtml from 'remark-html'

const file = await unified()
    .use(remarkParse)
    .use(remarkHtml)
    .process('# Hello, *Mercury*!')

console.log(String(file)) // => '<h1>Hello, <em>Mercury</em>!</h1>'
```

</details>

With another plugin, you can turn this markdown:

```markdown
# Hi, Saturn!
```

…into the following markdown:

```markdown
## Hi, Saturn!
```

<details><summary>Show example code</summary>

```js
import {unified} from 'unified'
import remarkParse from 'remark-parse'
import remarkStringify from 'remark-stringify'
import {visit} from 'unist-util-visit'

const file = await unified()
    .use(remarkParse)
    .use(myRemarkPluginToIncreaseHeadings)
    .use(remarkStringify)
    .process('# Hi, Saturn!')

console.log(String(file)) // => '## Hi, Saturn!'

/** @type {import('unified').Plugin<[], import('mdast').Root>} */
function myRemarkPluginToIncreaseHeadings() {
  return (tree) => {
    visit(tree, (node) => {
      if (node.type === 'heading') {
        node.depth++
      }
    })
  }
}
```

</details>

**Comment by BeLi4L** [comment]
Wow much better, I'll do that! :+1:

**Review by wooorm — APPROVED** [review]

**Comment by wooorm** [comment]
Oh, one small thing! The tests are failing, because by default they don’t want HTML in markdown.
You can solve this by changing package.json:

```diff
  "remarkConfig": {
    "plugins": [
-     "preset-wooorm"
+     "remark-preset-wooorm",
+     [
+       "remark-lint-no-html",
+       false
+     ]
    ]
  },
```

**Comment by BeLi4L** [comment]
Done, thank you :D

**Comment by BeLi4L** [comment]
@wooorm I tried your suggested changes, and also with `"preset-wooorm"` instead of `"remark-preset-wooorm"`, but I have another error now :sweat_smile:

**Review by wooorm — APPROVED** [review]

**Comment by wooorm** [comment]
Thank you!

**Pull request merged**
