### PR TITLE
Support for fenced code block info string

### PR DESCRIPTION
**Pull request by arobase-che**
Hi \o

The discussion is on the corresponding issue remarkjs/remark#342

Spoiler: It's about info string ;)

💘

### CODE REVIEW

**Comment by wooorm** [comment]
Build failed for some reason, I restarted it and now it’s green again!

**Comment by arobase-che** [comment]
¯\_(ツ)_/¯

**Comment by wooorm** [comment]
@arobase-che Could you update the code here to match syntax-tree/mdast#22?

**Comment by arobase-che** [comment]
Humm, it's already done. See [that comment](https://github.com/syntax-tree/mdast/pull/22#issuecomment-409415274). I updated the two the same day (night ...).

**Comment by wooorm** [comment]
@arobase-che Sorry, missed it!  Soooo, I was in the process of merging this, but hmm, from what I read in the commonmark spec they call the whole thing the info string (I still like info instead of info string). However, as we’re removing the lang from it, I’m not sure `info` is still fitting. Would it make sense to use `meta` instead? I’m not sure where I saw it today, but I like it:

```
~~~js foo bar baz
   ^^^^^^^^^^^^^^ info
      ^^^^^^^^^^^ meta
   ^^ lang
console.log('!')
~~~
```

/CC @Hypercubed

**Comment by ChristopherBiscardi** [comment]
Would love to see this get merged as we're getting requests for support in downstream projects ([gatsby-mdx](https://github.com/ChristopherBiscardi/gatsby-mdx/issues/76) and [mdx](https://github.com/mdx-js/mdx/issues/141)).

Is there anything I can do to help move this along? It looks like it might just need final review.

**Comment by wooorm** [comment]
Landed!

**Pull request merged**
