### PR TITLE
[WIP] test: migrate test suite to node:test

### PR DESCRIPTION
**Pull request by ChristianMurphy**
### Initial checklist

*   [x] I read the support docs 
*   [x] I read the contributing guide 
*   [x] I agree to follow the code of conduct 
*   [x] I searched issues and couldn’t find anything (or linked relevant results below) 
*   [x] If applicable, I’ve added docs and tests

### Description of changes

Migrates test suite from `tape` to `node:test`.

TODO:
- [ ] resolve race condition in fixture test suite

### CODE REVIEW

**Comment by wooorm** [comment]
Shoot, sorry, just did that :'(

**Comment by ChristianMurphy** [comment]
No worries, thanks @wooorm !

**Comment by wooorm** [comment]
Here’s the commit: https://github.com/remarkjs/remark/commit/f4ac350a981573ea91507bf5f3930606a529a0a6.

What race condition did you run into?

**Comment by ChristianMurphy** [comment]
in fixtures a bunch of
```
✖ {fixture name}
  'test did not finish before its parent and was cancelled'
```

it looks like you resolved that by `await`ing `t.test`?

**Comment by wooorm** [comment]
Yeah! `await t.test` is important, didn’t know that either.

But tests are so fast now with `node:test`, it finishes immediately.
Before, tape was super slow and running into memory stuff, hence the `setImmediate`s!

**Pull request closed without merging**
